version: '3.3'
services:
  dev-db:
    image : mongo:latest
    container_name: mongodb
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    networks:
      - nesjs-network
    restart: always

networks:
    nesjs-network:
      driver: bridge